
version: '3'

services:

  db:
    image: postgres:11
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: skatscoring
      POSTGRES_PASSWORD: skatscoringpwd

  adminer:
    depends_on:
      - db
    image: adminer:4.7.3
    ports:
      - 8080:8080

volumes:
  db-data: